services:
  pdf2zh-server:
    image: zotero-pdf2zh
    container_name: zotero-pdf2zh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 默认用官方 raw；可用环境变量覆盖
        SERVER_ZIP_URL: ${ZOTERO_PDF2ZH_SERVER_FILE_DOWNLOAD_URL:-https://raw.githubusercontent.com/guaguastandup/zotero-pdf2zh/main/server.zip}

        # ——可选镜像（按需取消注释其一）——
        # 1) 给原始链接加代理前缀（需 Dockerfile 已有 ARG GITHUB_PROXY_PREFIX）
        # GITHUB_PROXY_PREFIX: "https://ghproxy.net/"

        # 2) 直接把 SERVER_ZIP_URL 切到 jsDelivr（公开仓库单文件直链 CDN）
        # SERVER_ZIP_URL: "https://cdn.jsdelivr.net/gh/guaguastandup/zotero-pdf2zh@main/server.zip"
        
    environment:
      PORT: "8890"
      TZ: Asia/Shanghai
      ZOTERO_PDF2ZH_FROM_IMAGE: awwaawwa/pdfmathtranslate-next:latest
    volumes:
      - ./translated:/app/server/translated
      - ./config:/app/server/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8890:8890"
    restart: unless-stopped
