name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install deps
              run: |
                  cd plugin/ && npm install

            - name: Run Lint
              run: |
                  cd plugin/ && npm run lint:check

    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install deps
              run: |
                  cd plugin/ && npm install

            - name: Run Build
              run: |
                  cd plugin/ && npm run build

            - name: Upload build result
              uses: actions/upload-artifact@v4
              with:
                  name: build-result
                  path: |
                      cd plugin/ && build
