name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  # 为 plugin/package-lock.json 启用缓存
                  cache: 'npm'
                  cache-dependency-path: plugin/package-lock.json

            - name: Install deps
              run: |
                  cd plugin/ && npm install

            - name: Run Lint
              run: |
                  cd plugin/ && npm run lint:check

    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  # 为 plugin/package-lock.json 启用缓存
                  cache: 'npm'
                  cache-dependency-path: plugin/package-lock.json

            - name: Install deps
              run: |
                  cd plugin/ && npm install

            - name: Run Build
              run: |
                  cd plugin/ && npm run build

            # ------------------- 这里是修改的部分 -------------------
            - name: Upload build result
              uses: actions/upload-artifact@v4
              with:
                  name: build-result
                  # 'path' 参数需要的是文件路径，而不是命令
                  # 假设构建产物在 plugin/build/ 目录下
                  path: plugin/build
            # ----------------------------------------------------