name: Release

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # 将 GITHUB_TOKEN 设置为环境变量，以便后续的 gh 命令使用
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: cd plugin/ && npm install

      - name: Build
        run: |
          cd plugin/ && npm run build

      - name: Release plugin to GitHub
        run: |
          cd plugin/ && npm run release
          sleep 1s

      # ------------------- 新增的步骤 -------------------
      - name: Upload server.zip to Release
        # 使用 GitHub CLI (gh) 将根目录的 server.zip 上传到刚刚创建的 release 中
        # ${{ github.ref_name }} 会自动获取触发工作流程的 tag 名称 (例如 v1.2.3)
        run: gh release upload ${{ github.ref_name }} server.zip
      # ----------------------------------------------------

      - name: Notify release
        uses: apexskier/github-release-commenter@v1
        continue-on-error: true
        with:
          # 这个 action 也需要 GITHUB_TOKEN，但我们已经在 job 级别设置了 env
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # (可选，因为已在 job env 中定义)
          comment-template: |
            :rocket: _This ticket has been resolved in {release_tag}. See {release_link} for release notes._